# defining numpy array

In [2]:
import numpy as np
a=[1,2,3]
b=np.array(a)
type(b)

numpy.ndarray

In [3]:
# set datatype
b=[1,2,3,4]
print(np.array(b,dtype='float32'))

[1. 2. 3. 4.]


# Creating numpy array

In [4]:
# array with only 0
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# array with

# NumPy Array Attributes

In [6]:
import numpy as np
np.random.seed(1) # seed for reproducibility
x1= np.random.randint(10, size=6) #one- dimensional array
x2=np.random.randint(10,size=(3,4))
print(x2)
print("size = ",x2.size)
print("dimension = ",x2.ndim)
print("shape = ",x2.shape)
print("datatype = ",x2.dtype) # datatype 
print("itemsize = ",x2.itemsize) #size of an element
print("nbytes = ",x2.nbytes) # total size of elements


[[1 7 6 9]
 [2 4 5 2]
 [4 2 4 7]]
size =  12
dimension =  2
shape =  (3, 4)
datatype =  int32
itemsize =  4
nbytes =  48


# Array Indexing : Accessing Elements

In [7]:
x1

array([5, 8, 9, 5, 0, 0])

In [8]:
x1[0]

5

In [9]:
#Accessing 2d array
np.random.seed(0)
x3=np.random.randint(10,size=(3,3),dtype=int)
print(x3)
print(x3[0,0],x3[1,1],x3[2,2]) #diagonal elements


[[5 0 3]
 [3 7 9]
 [3 5 2]]
5 7 2


# Array Slicing : Accessing Subarray
## x[start:stop:step]


# Subarray as no copy views
## array slices return views rather than copies of the array data


In [10]:
np.random.seed(0)
x4=np.random.randint(10,size=(3,3),dtype=int)
print(x4,end="\n")
#subarray
print(x4[1],end="\n")
print(x4[1:3,1:3])

[[5 0 3]
 [3 7 9]
 [3 5 2]]
[3 7 9]
[[7 9]
 [5 2]]


In [11]:
x2=x4[1:3,1:3]
print(x2)
x2[0,0]=99
print(x2)
print(x4)

[[7 9]
 [5 2]]
[[99  9]
 [ 5  2]]
[[ 5  0  3]
 [ 3 99  9]
 [ 3  5  2]]


# Now if we modify this subarray, we'll see that the original array is changed! 

## This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.



# Creating Copies of Array 

In [16]:
x5=x2.copy()
print(x5)
x5[0,0]=0
print("x5",x5)
print("x2",x2) # no changes reflected back

[[99  9]
 [ 5  2]]
x5 [[0 9]
 [5 2]]
x2 [[99  9]
 [ 5  2]]


# Array Arithmetic

In [17]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [18]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


# Exponents , logarithms and Trigno

In [20]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [21]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [ ]:
np.sum = compute sum of elements
np.prod =Compute product of elements
np.mean = Compute mean of elements
np.std = Compute standard deviation
np.var = 	Compute variance