# defining numpy array

In [2]:
import numpy as np
a=[1,2,3]
b=np.array(a)
type(b)

numpy.ndarray

In [6]:
# set datatype
b=[1,2,3,4]
print(np.array(b,dtype='float32'))

[1. 2. 3. 4.]


# Creating numpy array

In [9]:
# array with only 0
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# array with

# NumPy Array Attributes

In [25]:
import numpy as np
np.random.seed(1) # seed for reproducibility
x1= np.random.randint(10, size=6) #one- dimensional array
x2=np.random.randint(10,size=(3,4))
print(x2)
print("size = ",x2.size)
print("dimension = ",x2.ndim)
print("shape = ",x2.shape)
print("datatype = ",x2.dtype) # datatype 
print("itemsize = ",x2.itemsize) #size of an element
print("nbytes = ",x2.nbytes) # total size of elements


[[1 7 6 9]
 [2 4 5 2]
 [4 2 4 7]]
size =  12
dimension =  2
shape =  (3, 4)
datatype =  int32
itemsize =  4
nbytes =  48


# Array Indexing : Accessing Elements

In [26]:
x1

array([5, 8, 9, 5, 0, 0])

In [27]:
x1[0]

5

In [ ]:
#Accessing 2d array
np.random.seed(0)
x3=np.random.randint(10,size=(3,3),dtype=int)
print(x3)
print(x3[0,0],x3[1,1],x3[2,2]) #diagonal elements


# Array Slicing : Accessing Subarray
## x[start:stop:step]


# Subarray as no copy views
## array slices return views rather than copies of the array data


In [63]:
np.random.seed(0)
x4=np.random.randint(10,size=(3,3),dtype=int)
print(x4,end="\n")
#subarray
print(x4[1],end="\n")
print(x4[1:3,1:3])

[[5 0 3]
 [3 7 9]
 [3 5 2]]
[3 7 9]
[[7 9]
 [5 2]]


In [67]:
x2=x4[1:3,1:3]
print(x2)
x2[0,0]=99
print(x2)
print(x4)

[[99  9]
 [ 5  2]]
[[99  9]
 [ 5  2]]
[[ 5  0  3]
 [ 3 99  9]
 [ 3  5  2]]


# Now if we modify this subarray, we'll see that the original array is changed! 

## This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.



# Creating Copies of Array 